# Generated by Django 4.2.30 on 2026-07-04 12:11

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
            ],
        ),
    ]
