# Generated by Django 4.2.30 on 2026-07-20 16:28

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentchunk_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
