# Generated by Django 4.2.30 on 2026-07-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentchunk_chunk_embedding_hnsw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
