# Generated by Django 4.2.30 on 2026-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_documentchunk_chunk_embedding_hnsw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_chunks', models.ManyToManyField(blank=True, related_name='chat_messages', to='documents.documentchunk')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
